image: "python:3.5"

before_script:
  - python3 -V

stages:
  - test

test_regex:
  stage: test
  script: 
    - cd tests/ 
    - python3 RegexTester.py
  allow_failure: true

test_lexer:
    stage: test
    script: 
      - cd tests/
      - ./LexerTester.sh
    allow_failure: true
