image: "python:3.5"

before_script:
  - python3 -V

stages:
  - test

test_lexer:
  stage: test
  script: 
    - cd tests/ 
    - python3 LexerTester.py -v

test_parser:
  stage: test
  script:
    - cd tests/
    - python3 ParserTester.py -v
