#!/usr/bin/env python3

from util import TOKEN

TOKEN_SYNTAX = {
    TOKEN.VAR             : "var",
    TOKEN.IF              : "if",
    TOKEN.ELIF            : "elif",
    TOKEN.ELSE            : "else",
    TOKEN.WHILE           : "while",
    TOKEN.FOR             : "for",
    TOKEN.RETURN          : "return",
    TOKEN.BREAK           : "break",
    TOKEN.CONTINUE        : "continue",
    TOKEN.PREFIX          : "prefix",
    TOKEN.INFIXL          : "infixl",
    TOKEN.INFIXR          : "infixr",
    TOKEN.TYPESYN         : "type",
    TOKEN.BOOL            : "bool",
    TOKEN.EMPTY_LIST      : "[]",
    TOKEN.CHAR            : "char",
    TOKEN.INT             : "int",
    TOKEN.STRING          : "string",
    TOKEN.PAR_OPEN        : "(",
    TOKEN.PAR_CLOSE       : ")",
    TOKEN.CURL_OPEN       : "{",
    TOKEN.CURL_CLOSE      : "}",
    TOKEN.BRACK_OPEN      : "[",
    TOKEN.BRACK_CLOSE     : "]",
    TOKEN.SEMICOLON       : ";",
    TOKEN.ACCESSOR        : "Accessor",
    TOKEN.IDENTIFIER      : "Identifier",
    TOKEN.OP_IDENTIFIER   : "Operator",
    TOKEN.TYPE_IDENTIFIER : "Type",
    TOKEN.IMPORT          : "import",
    TOKEN.FROM            : "from",
    TOKEN.AS              : "as",
    TOKEN.FILENAME        : "filename",
    TOKEN.IMPORTALL       : "importall"
}
